{% set name = "OneAgent-SDK-for-C" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Dynatrace/OneAgent-SDK-for-C/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4cb1d9385d24f5fe6a35882d0bf506f9a9206db3d8134e7aee1d47ac0f533968

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}

test:
  commands:
    - test -f "${PREFIX}/lib/libonesdk_shared.so"
    - test ! -f "${PREFIX}/lib/libonesdk_static.a"

about:
  home: https://github.com/Dynatrace/OneAgent-SDK-for-C
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Enables custom tracing of native applications in Dynatrace

extra:
  recipe-maintainers:
    - janjagusch
